# Increases the amount of memory Gradle can use and optimizes the GC
	# -XX:+UseZGC
	org.gradle.jvmargs=-Xmx4G
# Helps with build times
	org.gradle.parallel=true
# Caches Dependencies for faster build times.
	org.gradle.caching=true

# Fabric Properties
	# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
    minecraft_version=26.1
	loader_version=0.18.4

# Mod Properties
    mod_id = particletweaks
	mod_version = 3.0.1
	maven_group = net.lunade
	archives_base_name = ParticleTweaks

# Dependencies
    fabric_api_version=0.144.0+26.1
    frozenlib_version=2.4.2-mc26.1
# External Mods
    modmenu_version=18.0.0-alpha.6
    cloth_config_version=20.0.149
    wilderwild_version=4.2.5-mc26.1
    trailiertales_version=1.2-mc1.21.11

# Optimization
    sodium_version=mc26.1-0.8.7-fabric
    run_sodium = true
