# Increases the amount of memory Gradle can use and optimizes the GC
	# -XX:+UseZGC
	org.gradle.jvmargs=-Xmx4G
# Helps with build times
	org.gradle.parallel=true
# Caches Dependencies for faster build times.
	org.gradle.caching=true

# Fabric Properties
	# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
    minecraft_version=26.1-pre-2
	loader_version=0.18.4

# Mod Properties
    mod_id = particletweaks
	mod_version = 3.0.1
	maven_group = net.lunade
	archives_base_name = ParticleTweaks

# Dependencies
    fabric_api_version=0.143.13+26.1

# External Mods
    modmenu_version=18.0.0-alpha.5
    cloth_config_version=20.0.149
    fallingleaves_version=2.0.0+1.21.5
    wilderwild_version=4.2.3-mc26.1-pre-2
    trailiertales_version=1.2-mc1.21.11
    frozenlib_version=2.4-mc26.1-pre-2
    makebubblespop_version=0.3.1-fabric

# Optimization
    sodium_version=mc1.21.11-0.8.0-fabric
    run_sodium = false
