# Increases the amount of memory Gradle can use and optimizes the GC
	# -XX:+UseZGC
	org.gradle.jvmargs=-Xmx4G
# Helps with build times
	org.gradle.parallel=true
# Caches Dependencies for faster build times.
	org.gradle.caching=true

# Fabric Properties
	# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
    minecraft_version=1.21.9
    quilt_mappings=1.21+build.18
    parchment_mappings=1.21:2024.07.28
	loader_version=0.17.2

# Mod Properties
    mod_id = particletweaks
	mod_version = 2.1.5
	maven_group = net.lunade
	archives_base_name = ParticleTweaks

# Dependencies
    fabric_api_version=0.133.14+1.21.9

# External Mods
    modmenu_version=16.0.0-rc.1
    cloth_config_version=20.0.148
    fallingleaves_version=2.0.0+1.21.5
    wilderwild_version=4.1.1-mc1.21.9
    trailiertales_version=1.1.12-mc1.21.9
    frozenlib_version=2.2.1-mc1.21.9
    makebubblespop_version=0.3.1-fabric

# Optimization
    sodium_version=mc1.21.6-0.6.13-fabric
    run_sodium = false
    indium_version = 1.0.34+mc1.21
    run_indium = false
